# https://hub.docker.com/r/library/node/tags/
image: node:12

stages:
  - test
  - deploy

run_tests:
  stage: test
  script:
    - npm ci
    - cp .env.example .env
    - npm run prettier:inspect
    - npm run lint:inspect
    - npm run stylelint:inspect
    - npm run test

deploy_to_dev:
  stage: deploy
  only:
    - dev
  script:
    - echo "Deployed to dev-server"

deploy_to_stage:
  stage: deploy
  only:
    - stage
  script:
    - echo "Deployed to stage-server"

deploy_to_prod:
  stage: deploy
  only:
    - master
  script:
    - echo "Deployed to production-server"
